services:
  - type: web
    name: elpodiomp
    env: node
    region: oregon
    plan: free
    buildCommand: npm install
    startCommand: node server.js
    domains:
      - elpodiomp.com.ar
      - www.elpodiomp.com.ar
      - tech.elpodiomp.com.ar
      - food.elpodiomp.com.ar
      - hogar.elpodiomp.com.ar
    envVars:
      - key: PORT
        value: "3000"
      - key: DOMAIN
        value: elpodiomp.com.ar
      - key: BASE_URL
        value: https://elpodiomp.com.ar
      - key: MELI_CLIENT_ID
        sync: false
      - key: MELI_CLIENT_SECRET
        sync: false
      - key: MELI_ACCESS_TOKEN
        sync: false
      - key: GEMINI_API_KEY
        sync: false
      - key: ADMIN_PASSWORD
        value: podio2026
